# coding=utf-8
import unittest
from msprobe.mindspore.compare.layer_mapping import get_layer_mapping

ms_module_list = {'Cell.wezp.WOG.0': {'origin_data': 'Cell.wezp.WOG.forward.0',
                                                  'scope': None,
                                                  'stack': None},
                  'Cell.hks.XModel.0': {'origin_data': 'Cell.hks.XModel.backward.0',
                                        'scope': None,
                                        'stack': None},
                  'Cell.hks.tioa.YModel.0': {'origin_data': 'Cell.hks.tioa.YModel.backward.0',
                                                              'scope': 'Cell.hks.XModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.AModel.0': {'origin_data': 'Cell.hks.tioa.fgh.AModel.backward.0',
                                                 'scope': 'Cell.hks.tioa.YModel.backward.0',
                                                 'stack': None},
                  'Cell.hks.tioa.fgh.ty.BModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.BModel.backward.0',
                                                    'scope': 'Cell.hks.tioa.fgh.AModel.backward.0',
                                                    'stack': None},
                  'Cell.hks.tioa.fgh.ty.kl.GModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.kl.GModel.backward.0',
                                                       'scope': 'Cell.hks.tioa.fgh.ty.BModel.backward.0',
                                                       'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.CModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                          'scope': 'Cell.hks.tioa.fgh.ty.wer.6.er.DModel.backward.0',
                                                          'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.DModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.DModel.backward.0',
                                                             'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                             'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.EModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.EModel.backward.0',
                                                                   'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.DModel.backward.0',
                                                                   'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.bcd.DModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.bcd.DModel.forward.0',
                                                                       'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.EModel.forward.0',
                                                                       'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.abc.EModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.abc.EModel.forward.0',
                                                                       'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.EModel.forward.0',
                                                                       'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.tui.FModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.tui.FModel.backward.0',
                                                                 'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.DModel.backward.0',
                                                                 'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.er.tui.bcd.DModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.er.tui.bcd.DModel.forward.0',
                                                                     'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.tui.FModel.forward.0',
                                                                     'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.aqz.GModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.aqz.GModel.backward.0',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.iuta.GModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.iuta.GModel.backward.0',
                                                               'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                               'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.backward.0',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.1': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.backward.1',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.nmz.GModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.nmz.GModel.backward.0',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.er.DModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.IModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.IModel.backward.0',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.FModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.FModel.backward.0',
                                                                  'scope': 'Cell.hks.tioa.fgh.ty.wer.5.opb.IModel.backward.0',
                                                                  'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.bcd.DModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.bcd.DModel.forward.0',
                                                                      'scope': 'Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.FModel.forward.0',
                                                                      'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.EModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.EModel.backward.0',
                                                                  'scope': 'Cell.hks.tioa.fgh.ty.wer.5.opb.IModel.backward.0',
                                                                  'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.bcd.DModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.bcd.DModel.forward.0',
                                                                      'scope': 'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.EModel.forward.0',
                                                                      'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.abc.EModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.abc.EModel.forward.0',
                                                                      'scope': 'Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.EModel.forward.0',
                                                                      'stack': None},
                  'Cell.hks.tioa.fgh.ty.wer.5.itw.GModel.0': {'origin_data': 'Cell.hks.tioa.fgh.ty.wer.5.itw.GModel.backward.0',
                                                              'scope': 'Cell.hks.tioa.fgh.ty.wer.5.CModel.backward.0',
                                                              'stack': None},
                  'Cell.hks.tioa.fgh.efg.JModel.0': {'origin_data': 'Cell.hks.tioa.fgh.efg.JModel.forward.0',
                                                     'scope': 'Cell.hks.tioa.fgh.AModel.forward.0',
                                                     'stack': None},
                  'Cell.zwaw.KModel.0': {'origin_data': 'Cell.zwaw.KModel.forward.0',
                                         'scope': None,
                                         'stack': None},
                  'Cell.zwaw.swa.LModel.0': {'origin_data': 'Cell.zwaw.swa.LModel.forward.0',
                                             'scope': 'Cell.zwaw.KModel.forward.0',
                                             'stack': None},
                  'Cell.zwaw.swa.LModel.1': {'origin_data': 'Cell.zwaw.swa.LModel.forward.1',
                                             'scope': None,
                                             'stack': None},
                  'Cell.zwaw.swa.ewa.MModel.0': {'origin_data': 'Cell.zwaw.swa.ewa.MModel.forward.0',
                                                 'scope': 'Cell.zwaw.swa.LModel.forward.0',
                                                 'stack': None},
                  'Cell.zwaw.swa.ewa.MModel.1': {'origin_data': 'Cell.zwaw.swa.ewa.MModel.forward.1',
                                                 'scope': 'Cell.zwaw.swa.LModel.forward.1',
                                                 'stack': None}}
pt_module_list = {'Module.module.YFModel.0': {'origin_data': 'Module.module.YFModel.backward.0',
                                                    'scope': None,
                                                    'stack': None},
                  'Module.module.module.YModel.0': {'origin_data': 'Module.module.module.YModel.backward.0',
                                                      'scope': None,
                                                      'stack': None},
                  'Module.module.module.fgh.AModel.0': {'origin_data': 'Module.module.module.fgh.AModel.backward.0',
                                                        'scope': None,
                                                        'stack': None},
                  'Module.module.module.fgh.ty.BModel.0': {'origin_data': 'Module.module.module.fgh.ty.BModel.backward.0',
                                                           'scope': None,
                                                           'stack': None},
                  'Module.module.module.fgh.ty.kl.ZModel.0': {'origin_data': 'Module.module.module.fgh.ty.kl.ZModel.backward.0',
                                                              'scope': None,
                                                              'stack': None},
                  'Module.module.module.fgh.ty.wer.0.CModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                 'scope': None,
                                                                 'stack': None},
                  'Module.module.module.fgh.ty.wer.0.aqz.ZModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.aqz.ZModel.backward.0',
                                                                     'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                     'stack': None},
                  'Module.module.module.fgh.ty.wer.0.iuta.ZModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.iuta.ZModel.backward.0',
                                                                      'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                      'stack': None},
                  'Module.module.module.fgh.ty.wer.0.nmz.ZModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.nmz.ZModel.backward.0',
                                                                     'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                     'stack': None},
                  'Module.module.module.fgh.ty.wer.0.opb.IModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.opb.IModel.backward.0',
                                                                     'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                     'stack': None},
                  'Module.module.module.fgh.ty.wer.0.opb.tyyu.EModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.opb.tyyu.EModel.backward.0',
                                                                          'scope': 'Module.module.module.fgh.ty.wer.0.opb.IModel.backward.0',
                                                                          'stack': None},
                  'Module.module.module.fgh.ty.wer.0.opb.bhg.FModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.opb.bhg.FModel.backward.0',
                                                                         'scope': 'Module.module.module.fgh.ty.wer.0.opb.IModel.backward.0',
                                                                         'stack': None},
                  'Module.module.module.fgh.ty.wer.0.itw.ZModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.itw.ZModel.backward.0',
                                                                     'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                     'stack': None},
                  'Module.module.module.fgh.ty.wer.0.ti.DModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.ti.DModel.backward.0',
                                                                    'scope': 'Module.module.module.fgh.ty.wer.0.CModel.backward.0',
                                                                    'stack': None},
                  'Module.module.module.fgh.ty.wer.0.ti.io.NModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.ti.io.NModel.backward.0',
                                                                       'scope': 'Module.module.module.fgh.ty.wer.0.ti.DModel.backward.0',
                                                                       'stack': None},
                  'Module.module.module.fgh.ty.wer.0.ti.nmzq.EModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.ti.nmzq.EModel.backward.0',
                                                                         'scope': 'Module.module.module.fgh.ty.wer.0.ti.DModel.backward.0',
                                                                         'stack': None},
                  'Module.module.module.fgh.ty.wer.0.ti.yu.FModel.0': {'origin_data': 'Module.module.module.fgh.ty.wer.0.ti.yu.FModel.backward.0',
                                                                       'scope': 'Module.module.module.fgh.ty.wer.0.ti.DModel.backward.0',
                                                                       'stack': None},
                  'Module.module.module.fgh.efg.JModel.0': {'origin_data': 'Module.module.module.fgh.efg.JModel.forward.0',
                                                            'scope': 'Module.module.module.fgh.AModel.forward.0',
                                                            'stack': None}}
layer_mapping = {'DModel': {'tui': 'yu', 'nmzqz': 'nmzq'}, 'CModel': {'er': 'ti'}, 'Embedding': {'fda': 'req'}, 'IModel': {
    'qwt': 'bhg', 'zsq': 'tyyu'}, 'XModel': {'tioa': 'module'}, 'Cell': {'hks': 'module'}, 'wer': {'5': '0', '6': '1', '7': '2', '8': '3', '9': '4'}}

exptect_result = [
    ('Cell.hks.XModel.0', 'Module.module.YFModel.0'),
    ('Cell.hks.tioa.YModel.0', 'Module.module.module.YModel.0'),
    ('Cell.hks.tioa.fgh.AModel.0',
     'Module.module.module.fgh.AModel.0'),
    ('Cell.hks.tioa.fgh.efg.JModel.0',
     'Module.module.module.fgh.efg.JModel.0'),
    ('Cell.hks.tioa.fgh.ty.BModel.0',
     'Module.module.module.fgh.ty.BModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.CModel.0',
     'Module.module.module.fgh.ty.wer.0.CModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.nmz.GModel.0',
     'Module.module.module.fgh.ty.wer.0.nmz.ZModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.DModel.0',
     'Module.module.module.fgh.ty.wer.0.ti.DModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.tui.FModel.0',
     'Module.module.module.fgh.ty.wer.0.ti.yu.FModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.tui.bcd.DModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.EModel.0',
     'Module.module.module.fgh.ty.wer.0.ti.nmzq.EModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.bcd.DModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.er.nmzqz.abc.EModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.aqz.GModel.0',
     'Module.module.module.fgh.ty.wer.0.aqz.ZModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.btz.HModel.1', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.itw.GModel.0',
     'Module.module.module.fgh.ty.wer.0.itw.ZModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.IModel.0',
     'Module.module.module.fgh.ty.wer.0.opb.IModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.FModel.0',
     'Module.module.module.fgh.ty.wer.0.opb.bhg.FModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.qwt.bcd.DModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.EModel.0',
     'Module.module.module.fgh.ty.wer.0.opb.tyyu.EModel.0'),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.bcd.DModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.opb.zsq.abc.EModel.0', None),
    ('Cell.hks.tioa.fgh.ty.wer.5.iuta.GModel.0',
     'Module.module.module.fgh.ty.wer.0.iuta.ZModel.0'),
    ('Cell.hks.tioa.fgh.ty.kl.GModel.0',
     'Module.module.module.fgh.ty.kl.ZModel.0'),
    ('Cell.wezp.WOG.0', None),
    ('Cell.zwaw.KModel.0', None),
    ('Cell.zwaw.swa.LModel.0', None),
    ('Cell.zwaw.swa.LModel.1', None),
    ('Cell.zwaw.swa.ewa.MModel.0', None),
    ('Cell.zwaw.swa.ewa.MModel.1', None)]


class TestLayerMapping(unittest.TestCase):

    def test_layer_mapping_for_cell(self):
        res = get_layer_mapping(ms_module_list, pt_module_list, layer_mapping)
        res.sort()
        exptect_result.sort()
        self.assertListEqual(res, exptect_result)
