class TableConstant:

    RANK_SET = "rank_set"
    STEP = "step"
    RANK_ID = "rank_id"
    TYPE = "type"
    HCCL_OP_NAME = "hccl_op_name"
    GROUP_NAME = "group_name"
    START_TIMESTAMP = "start_timestamp"
    ELAPSED_TIME = "elapse_time"
    TRANSIT_TIME = "transit_time"
    WAIT_TIME = "wait_time"
    SYNCHRONIZATION_TIME = "synchronization_time"
    IDLE_TIME = "idle_time"
    SYNCHRONIZATION_TIME_RATIO = "synchronization_time_ratio"
    WAIT_TIME_RATIO = "wait_time_ratio"
    BAND_TYPE = "band_type"
    TRANSIT_SIZE = "transit_size"
    BANDWIDTH = "bandwidth"
    LARGE_PACKET_RATIO = "large_packet_ratio"
    PACKAGE_SIZE = "package_size"
    COUNT = "count"
    TOTAL_DURATION = "total_duration"
    SRC_RANK = "src_rank"
    DST_RANK = "dst_rank"
    TRANSPORT_TYPE = "transport_type"
    OPNAME = "op_name"
