[LOG]
# console_logging_level : DEBUG/INFO/WARNING/ERROR
console_logging_level = INFO
[ANALYSE]
# analysis_result_file : filename of analysis result
analysis_result_file = analysis_result_file.xlsx
# tune_ops_file: filename of tune op name list
tune_ops_file = operator_tuning_file.cfg
[THRESHOLD]
# operator_bound_ratio: (mte, cube, vector, scalar) ratio greater than this value will be checked in operator_bound_checker
operator_bound_ratio = 0.8
frequency_threshold = 0.05
[RULE-BUCKET]
# region : URL of different regions where can download rule yaml file
cn-north-9 = cnnorth9-modelarts-sdk
cn-southwest-2 = cnsouthwest2-modelarts-sdk
cn-north-7 = cnnorth7-modelarts-sdk